DECLARE @PRODUTO INT
DECLARE @QTD INT
DECLARE @QTDTRASF INT
DECLARE @QTDTOTAL INT
DECLARE @NUMNOTA INT
DECLARE @CHAVE NVARCHAR(44)

IF OBJECT_ID('TempDB.dbo.#PRODUTOS_INCINERACAO_FILIAL_752') IS NOT NULL
	DELETE #PRODUTOS_INCINERACAO_FILIAL_752
ELSE
	CREATE TABLE #PRODUTOS_INCINERACAO_FILIAL_752(
		FILIAL		varchar(50),
		COD			varchar(50),
		DV			varchar(50),
		DESCRICAO	varchar(50),
		QT_MOV2		varchar(50),
		TP_MOV		varchar(50),
		VENDA		varchar(50),
		TT_VENDA	varchar(50),
		CUSTO		varchar(50),
		TT_CMPG		varchar(50),
		DH_OCORR	varchar(50),
		NUMERONOTA	int,
		CHAVEACESSO	varchar(50),
		QT_NOTA		varchar(50)
	)  

DECLARE LOTE_CUR CURSOR FOR   
	SELECT 
		COD AS PRODUTO,
		CONVERT(NUMERIC,REPLACE(QT_MOV2,',','.')) AS QTD
	FROM [DBO].[PRODUTOS_INCINERACAO_LOJA_752_02_SS_004]
OPEN LOTE_CUR

FETCH NEXT FROM LOTE_CUR
INTO @PRODUTO,@QTD

WHILE @@FETCH_STATUS = 0  
BEGIN  
		SET @QTDTOTAL = 0
		DECLARE TRANSF_CAB_CUR CURSOR FOR   
			SELECT 
				CAB.TRCA_NR_NFTRANS,
				CAB.CHAVE_ACESSO_NFE,
				CONVERT(INT,DET.TRDE_QT_ATENDIDA)
			FROM [COSMOS_V14B].DBO.[TRANSF_CAB_ANTERIOR] CAB
				INNER JOIN  [COSMOS_V14B].DBO.[TRANSF_DET_ANTERIOR] DET 
					ON (CAB.TRCA_SQ_CAB = DET.TRCA_SQ_CAB) 
			WHERE DET.TRDE_CD_PRODUTO = @PRODUTO
				AND CAB.TRCA_CD_DEPOSITO IN (2)
				AND CAB.TRCA_CD_FILIAL = 752
			ORDER BY DET.TRDE_QT_ATENDIDA DESC

		OPEN TRANSF_CAB_CUR

		FETCH NEXT FROM TRANSF_CAB_CUR
		INTO @NUMNOTA,@CHAVE,@QTDTRASF

		SET @QTDTOTAL += @QTDTRASF	

		WHILE @@FETCH_STATUS = 0  
		BEGIN  
			INSERT #PRODUTOS_INCINERACAO_FILIAL_752
			SELECT 
					 FILIAL		
					,COD			
					,DV			
					,DESCRICAO	
					,QT_MOV2		
					,TP_MOV		
					,VENDA		
					,TT_VENDA	
					,CUSTO		
					,TT_CMPG		
					,DH_OCORR	
					,@NUMNOTA	
					,@CHAVE
					,@QTDTRASF	
			FROM [PRODUTOS_INCINERACAO_LOJA_752_02_SS_004]
			WHERE COD = @PRODUTO

			IF (@QTDTOTAL >= @QTD)
				BREAK

		FETCH NEXT FROM TRANSF_CAB_CUR
		INTO @NUMNOTA,@CHAVE,@QTDTRASF

		SET @QTDTOTAL += @QTDTRASF	

		END
		CLOSE TRANSF_CAB_CUR
		DEALLOCATE TRANSF_CAB_CUR

FETCH NEXT FROM LOTE_CUR   
    INTO @PRODUTO,@QTD
END
CLOSE LOTE_CUR
DEALLOCATE LOTE_CUR  

SELECT * 
FROM #PRODUTOS_INCINERACAO_FILIAL_752
ORDER BY COD
